ALTER TABLE upa
    ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN capacity DROP NOT NULL,
    ALTER COLUMN street DROP NOT NULL,
    ALTER COLUMN city DROP NOT NULL,
    ALTER COLUMN state DROP NOT NULL,
    ALTER COLUMN zip_code DROP NOT NULL;
